# Generated by Django 2.2 on 2021-01-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='referals',
            field=models.ManyToManyField(blank=True, related_name='refs', to='store.Shopper'),
        ),
        migrations.AddField(
            model_name='shopper',
            name='referer_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
