# Generated by Django 2.2 on 2021-02-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_shopper_used_coupons'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='orders',
            field=models.ManyToManyField(blank=True, to='store.Order'),
        ),
    ]
