# Generated by Django 2.2 on 2021-02-03 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_shopper_used_coupons'),
        ('api', '0002_auto_20210203_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default='n05df2kvzfir', max_length=12, unique=True)),
                ('pin', models.CharField(blank=True, max_length=4)),
                ('billing_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.Billing_Information')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Order')),
            ],
        ),
    ]
