# Generated by Django 2.2 on 2021-02-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210203_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_information',
            name='card_number',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='unique_id',
            field=models.CharField(default='zcjtltgvhwho', max_length=12, unique=True),
        ),
    ]
