# Generated by Django 2.2 on 2021-02-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210203_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='unique_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
